# -*- coding: utf-8 -*-
"""xai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-l8aRfoloYH11lXJ587eozUx1XHr7dBQ
"""

#%pip install shap

import shap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# class AutoEncoderSHAP:


class OtherModelSHAP:
  model = None
  score = None
  train_data=None
  test_data=None

  #xai를 구현 시 필요한 파라미터를 적용
  def __init__(self, model):
    self.model=model
  def novelty_contribution(self, train_data, test_data, score, threshold):
    self.train_data = train_data
    self.test_data = test_data
    self.score = score
    self.threshold = threshold
    model_name = type(self.model).__name__

    model_df = self.test_data.copy()
    model_df['anomaly_score']=self.score
    model_df.sort_values(by='anomaly_score', axis=0, ascending=False, inplace=True)
    novelties_df=model_df[model_df['anomaly_score']>threshold]
    novelties_df_index= novelties_df.index
    shap_list = []

    if model_name in ['MCD', 'LOF','GMM']:
      explainer = shap.KernelExplainer(self.model.decision_function, self.train_data.head(100).values)
    else:
      raise Exception('Wrong model name or Use AutoEncoderSHAP')


    for idx in novelties_df_index:
      record_to_explain = self.test_data.iloc[idx]
      shap_values = explainer.shap_values(record_to_explain, nsamples='auto')
      shap_list.append(shap_values)
    shap_values_all = pd.DataFrame(data = shap_list)
    shap_values_all.index=novelties_df_index.to_list()
    shap_values_all.columns= self.test_data.columns
    return shap_values_all